### ISSUE TITLE
关于项目启动的问题？

### ISSUE THREAD

**Issue by zz829740** [ecmadao/rxjs-example#1]
package.json里的scripts属性，build和dev-server怎么只写了目录，前面得加node命令吧？

**Comment by ecmadao** [comment]
@WJane 好问题。如果是普通的 js 文件，要运行起来的话是要通过`node xxx.js`没错，但是例如 webpack 这样的 node 包，其实在你安装它的过程中，它已经被赋予了直接执行的权限，并通过 PATH 环境变量创建了一个软链接，你可以在 `/usr/local/bin/` 文件夹下面找到对应的链接文件。如此以外，它的源码里面也会在第一行加上注释 ` #! /usr/bin/env node` ，表明通过 Node.js 进行解析。这样一来，该文件就具有直接执行权限，并且会在执行时用过 node 来解析了

不过这是在 Linux 系统的前提下，Windows 系统我就不了解了。。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by zz829740** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。

**Comment by WJane** [comment]
@ecmadao 原来是这样，很清楚了。不过windows的话，我亲测了一下的结果确实需要加node，否则无法识别命令。看了下windows的源码也没有那行注释，应该只是linux才会直接执行。
